### PR TITLE
Update winapi

### PR DESCRIPTION
**Pull request by MarnixKuijs**
- Updates winapi to 0.3.9 
- Get rid of -sys dependencies and use winapi instead.

### CODE REVIEW

**Comment by haraldh** [comment]
Thanks!

**Comment by haraldh** [comment]
released `uds_windows = "0.1.6"`

**Comment by MarnixKuijs** [comment]
Thank you 👍

**Comment by haraldh** [comment]
even 1.0.1 now 😀

**Comment by fanzeyi** [comment]
Because there is no issue enabled for this repo, I want to borrow this pr to ask if @haraldh would consider replacing winapi with [microsoft/windows-rs](https://github.com/microsoft/windows-rs). winapi-rs seems to be stagnated (I personally have two PRs pending for months), and the Micorsoft one seems to have everything this repo needs:  https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/win_sock/index.html 

If so, I can start looking into this, but I would like to hear your opinion first. 

Thanks.

**Comment by haraldh** [comment]
oops.. enabled "Issues"

**Comment by haraldh** [comment]
Yeah, I will accept PRs changing to windows-rs

**Pull request merged**
