### PR TITLE
New async io interfaces

### PR DESCRIPTION
**Pull request by TTWNO**
A fix-up of #8 

I understand you requested safety comments, however, it appears that safety comments are being generated for parts of the code unchanged by this PR.

### CODE REVIEW

**Comment by haraldh** [comment]
cargo fmt check failed

**Comment by haraldh** [comment]
I requested source code comments stating, why the `unsafe {}` sections are actually safe. Like:
```rust
  // SAFETY: the following unsafe section is safe, because ....
```

**Comment by haraldh** [comment]
See also https://std-dev-guide.rust-lang.org/policy/safety-comments.html#inside-safe-elements

**Comment by TTWNO** [comment]
> I requested source code comments stating, why the unsafe {} sections are actually safe.

I understand now.

**Comment by TTWNO** [comment]
Just checking if there's anything else I need to do to get this merged? Happy to get started on it ASAP :)

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
Maybe rebase on the current master

**Comment by haraldh** [comment]
Maybe rebase on the current master and squash some commits

**Comment by TTWNO** [comment]
Done!

**Comment by haraldh** [comment]
Thanks!

**Comment by haraldh** [comment]
released `1.1.0`

**Pull request merged**
